name: Run Shell Script with Parameters

on:
  push:
    branches:
      - main  # Specify the branch that triggers the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # You can use different runners like macos-latest or windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # This step checks out your repository so the workflow can access it

      - name: Set up shell script permissions
        run: chmod +x ./build.sh
        # Make sure the script is executable

      - name: Run shell script with parameters
        run: |
          set -x ./build.sh "node" "apt" "curl" "docker.io"
        # Replace `./path/to/your-script.sh` with the path to your script
        # Pass the required parameters to the script
